services:
  ollama:
    image: ollama/ollama:0.5.4
    container_name: bioma-ollama
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEPALIVE=-1
      - OLLAMA_DEBUG=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    volumes:
      - bioma-ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - bioma-network

  surrealdb:
    image: surrealdb/surrealdb:v2.1.4
    container_name: bioma-surrealdb
    command: start --no-banner --allow-all --bind 0.0.0.0:9123 --user root --pass root surrealkv://data/bioma.db
    user: "1000:1000"
    volumes:
      - bioma-surreal_data:/data
    ports:
      - "9123:9123"
    networks:
      - bioma-network

  init-volume:
    image: busybox
    container_name: bioma-init-volume
    volumes:
      - bioma-surreal_data:/data
    command: chown -R 1000:1000 /data

  markitdown:
    build:
      context: assets/scripts/markitdown
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    entrypoint: [ "gunicorn", "--bind", "0.0.0.0:5001", "markitdown_script:app" ]

  pdf-analyzer:
    build:
      context: ../pdf-document-layout-analysis
      dockerfile: Dockerfile
    container_name: pdf-document-layout-analysis
    entrypoint: [ "gunicorn", "-k", "uvicorn.workers.UvicornWorker", "--chdir", "./src", "app:app", "--bind", "0.0.0.0:5060", "--timeout", "10000" ]
    init: true
    restart: unless-stopped
    ports:
      - "5060:5060"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger-ui
    ports:
      - "80:8080"
    environment:
      - SWAGGER_JSON=/app/openapi.json
    volumes:
      - ./tools/rag_server/docs:/app

volumes:
  bioma-ollama_data:
  bioma-surreal_data:


networks:
  bioma-network:
    driver: bridge
